### ISSUE TITLE
train/val/test split file?

### ISSUE THREAD

**Issue by ronghanghu** [mjhucla/Google_Refexp_toolbox#2]
Hi Authors!

This is really great work! Can you distribute the training/validation/test split of your dataset as used in your paper http://arxiv.org/pdf/1511.02283v2.pdf ?

Thanks again!

**Comment by mjhucla** [comment]
Thanks for your interest! The validation and training data are stored in separated files when you finish downloading them. We have not released the test data yet. Will let you know when it is available.

**Comment by ronghanghu** [comment]
OK, I see. Thanks :)

**Comment by ronghanghu** [comment]
@mjhucla Do you have an estimated date of releasing the test data?

**Comment by n-askarian** [comment]
Hi,
Have you published the test split of your dataset?
